name: Sample GitHub Actions
run-name: GitHub sample actions -  @${{ github.actor }}
on: [push]
jobs:
  run-on-github-actions:
    runs-on: windows-latest
    steps: 
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
      - name: Checkout Files
        uses: actions/checkout@v1
      - name: List files after Checkout
        run: |
          pwd
          ls
          echo $GITHUB_SHA

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: "Suresh"
      - name: Log Greating Time
        run: echo "${{ steps.greet.outputs.time }}"
