name: Sample Shell Commands
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: [pull_request]

jobs:
    run-shell-command:
        runs-on: windows-latest
        steps:
            - name: echo a string
              run: echo "hello world"
            - name: echo multiline
              run: |
                  node -v
                  npm -v
    
    run-windows-command:
        runs-on: windows-latest
        needs: ["run-shell-command"]
        steps:
            - name: Directory powershell
              run: Get-Location
            - name: Directory bash
              run: pwd
              shell: bash